name: Vulplabs
favicon: null
layout_spectrum: 0.6123343338258564
typography_spectrum: 0.9315824043005705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.33815229730680585
  lightness: 0.7704529038164765
  saturation: 0.23029293166473508
  rhythmicContrast: 0.08500333176925778
purpose: []
